C:\Users\medad\Documents\University storage\Computer Aided Design\Solid elements submission\cad-file-exercise-1-Solid1
C:\Users\medad\Documents\University storage\Computer Aided Design\Solid elements submission\cad-file-exercise-1-Solid1
C:\Users\medad\Documents\University storage\Computer Aided Design\Solid elements submission\cad-file-exercise-2-SOlid1
C:\Users\medad\Documents\University storage\Computer Aided Design\Solid elements submission\cad-file-exercise-2-SOlid1
C:\Users\medad\Documents\University storage\Computer Aided Design\Solid elements submission\cad-file-exercise-2-SOlid1
